version: '3.1'
services:
  dbpatient:
    container_name: dbpatient
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dbpatient
    ports:
      - "5432:5432"



  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
#      PGADMIN_LISTEN_PORT = 80
    ports:
      - "5050:80"


#   networks:
#      -  mediscreennetwork
#networks:
#  mediscreennetwork:


